### ISSUE TITLE
Issues getting card to work 

### ISSUE THREAD

**Issue by johntdyer** [DBuit/thermostat-popup-card#3]
﻿My code from lovelace.yaml

```yaml

popup_cards:
  climate.family_room_nest:
    title: ""
    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.8)
      flex-direction: column
      margin: 0
      "--iron-icon-fill-color": "#FFF"
    card:
      type: custom:thermostat-popup-card
      entity: climate.family_room_nest
```
Then on my view I have

```yaml


  - title: "Lights"
    icon: mdi:speaker
    id: test
    panel: true
    cards:
          - type: "custom:homekit-card"
            entities:
              - title: Lights
                popup:
                  type: custom:light-popup-card
                  # scenesInARow: 2
                  brightnessWidth: 130px
                  brightnessHeight: 350px
                  switchWidth: 110px
                  switchHeight: 300px
                entities:
                  - entity: climate.family_room_nest
                  - entity: light.office_desk_left_light

                    popupExtend:
                      actions:
                        - scene: scene.office_early
                          color: "#FDCA64"
                          name: Early
                        - scene: scene.office_red
                          color: "red"
                          name: red
```

and the card renders, and shows the temp

<img width="266" alt="image" src="https://user-images.githubusercontent.com/58234/72684461-99f65680-3aae-11ea-906f-0adb78c1e93f.png">

However when I click the card i get the following 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/58234/72684475-b0041700-3aae-11ea-8f42-dce7950bd805.png">

however the light popup card works as I'd expect... 

<img width="785" alt="image" src="https://user-images.githubusercontent.com/58234/72684491-d9bd3e00-3aae-11ea-832e-6d7ce69aab11.png">

Im still trying to wrap my head around the pop-up card 'ecosystem' of cards, so its highly likely I just did something stupid because I dont understand it

**Comment by DBuit** [comment]
Hey,
Put the popup: part on the light entity. It now uses the light pop-up for all entities in that list.

**Comment by johntdyer** [comment]
Hey @DBuit , thanks for responding at all, especially on a weekend!!  Sorry for my naivety but afraid I am not sure what your suggesting I change to get this working.. Any chance you could rephrase ? ..

**Comment by DBuit** [comment]
Hey @johntdyer no problem!

You can do it like this so that the popup part of the card is on the specific light entity.
```
  - title: "Lights"
    icon: mdi:speaker
    id: test
    panel: true
    cards:
          - type: "custom:homekit-card"
            entities:
              - title: Lights
                entities:
                  - entity: climate.family_room_nest
                  - entity: light.office_desk_left_light
                    popup:
                        type: custom:light-popup-card
                        # scenesInARow: 2
                        brightnessWidth: 130px
                        brightnessHeight: 350px
                        switchWidth: 110px
                        switchHeight: 300px
                            actions:
                                - scene: scene.office_early
                                  color: "#FDCA64"
                                  name: Early
                                - scene: scene.office_red
                                  color: "red"
                                  name: red
```

**Comment by johntdyer** [comment]
@DBuit  so things are looking better with this config ( attaching for posterity sake) 
# popup_cards

```yaml
popup_cards:
  climate.family_room_nest:
    title: ""

    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.8)
      flex-direction: column
      margin: 0
      "--iron-icon-fill-color": "#FFF"
    card:
      type: custom:thermostat-popup-card
      entity: climate.family_room_nest



  light.office_desk_left_light:
    title: ""
    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.8)
      flex-direction: column
      margin: 0
      "--iron-icon-fill-color": "#FFF"
    card:
      type: custom:light-popup-card
      entity: light.office_desk_left_light
      icon: mdi:led-strip
      actionsInARow: 2
      brightnessWidth: 150px
      brightnessHeight: 400px
      switchWidth: 150px
      switchHeight: 400px
      actions:
        - service: scene.turn_on
          service_data:
            entity_id: scene.office_early
          color: "#FDCA64"
          name: Early
        - service: scene.turn_on
          service_data:
            entity_id: scene.office_red
          color: "red"
          name: Early
```
## View
```yaml
          - type: "custom:homekit-card"
            entities:
              - title: Climate
                entities:
                  - entity: climate.family_room_nest

          - type: "custom:homekit-card"
            entities:
              - title: Lights
                entities:
                  - entity: light.office_desk_left_light

```
---------------
but I still have a few more questions that I am hoping you can maybe clear up for me..

#1.  What is the significance of the name defined under `popup_cards` at the root of my lovelace?
#2 Why does it need to be named the same as the thermostat, and then again within the popup_cards config it needs to be defined again
#3. I seem to have to do a "force touch" to activate it on my macbook pro... I double click doesnt seem to work for me... 

```yaml
popup_cards:
  climate.family_room_nest:
    title: ""

    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.8)
      flex-direction: column
      margin: 0
      "--iron-icon-fill-color": "#FFF"
    card:
      type: custom:thermostat-popup-card
      entity: climate.family_room_nest
```

**Comment by DBuit** [comment]
Hi @johntdyer 

So to begin with the `popup_cards:` part is not part of the thermostat card and also not of the homekit-panel-card it is the configuration of thomas lovens browser_mod component. 
But to get back to your questions i think i can answer them.

1. The name of your entity right after `popup_cards` it the entity it will overwrite the default popup for. for the popup for climate.family_room_nest get overwritten. 
2. The reason you need to define it again is that the browser_mod is able to show all lovelace cards as a popup so this give the ability to open popup for other entities than the one your clicked so the second part is just the configuration for the card you are opening and because my pop-up cards needs to know what entity you want to control you have to set it.
3. The pop-up overwrites the default more-info pop-up home assistant gives you and that always works on a `hold` action maybe on macbook this is a force touch dont really know but don't think double click can be done.

But to help you a bit and maybe make it easier you don't have to use the `popup_cards:` part if you want do create what you now have. 
Because you use it in combination with my other card `custom:homekit-card` you can set the popups in this card and remove the `popup_cards:` part. this should also work:

```
  - title: "Lights"
    icon: mdi:speaker
    id: test
    panel: true
    cards:
      - type: "custom:homekit-card"
        entities:
          - title: Lights
            entities:
              - entity: climate.family_room_nest
                popup:
                  type: custom:thermostat-popup-card
              - entity: light.office_desk_left_light
                popup:
                  type: custom:light-popup-card
                  brightnessWidth: 130px
                  brightnessHeight: 350px
                  switchWidth: 110px
                  switchHeight: 300px
                  actions:
                    - scene: scene.office_early
                      color: "#FDCA64"
                      name: Early
                    - scene: scene.office_red
                      color: "red"
                      name: red
```
