### ISSUE TITLE
"Cannot add property useTemperature, object is not extensible" Problem with HA 0.106.1

### ISSUE THREAD

**Issue by CM000n** [DBuit/thermostat-popup-card#5]
Hello, since the update to Home Assistant 0.106.1 I get the following error message on pages where the thermostat card is used and this Lovelace page cannot be displayed

```
Cannot add property useTemperature, object is not extensible
type: 'custom:homekit-card'
breakOnMobile: true
statePositionTop: true
entities:
  - title: Klimakontrolle
    entities:
      - entity: climate.heizung_bad
        tap_action:
          action: call-service
          service: browser_mod.popup
          service_data:
            title: Thermostat
            style:
              position: fixed
              z-index: 999
              top: 0
              left: 0
              height: 100%
              width: 100%
              display: block
              align-items: center
              justify-content: center
              background: 'rgba(0, 0, 0, 0.8)'
              flex-direction: column
              margin: 0
              '--iron-icon-fill-color': '#FFF'
            card:
              type: 'custom:thermostat-popup-card'
              entity: climate.heizung_bad
              fullscreen: false
            deviceID:
              - this
      - entity: climate.heizung_buro
        tap_action:
          action: call-service
          service: browser_mod.popup
          service_data:
            title: Thermostat
            style:
              position: fixed
              z-index: 999
              top: 0
              left: 0
              height: 100%
              width: 100%
              display: block
              align-items: center
              justify-content: center
              background: 'rgba(0, 0, 0, 0.8)'
              flex-direction: column
              margin: 0
              '--iron-icon-fill-color': '#FFF'
            card:
              type: 'custom:thermostat-popup-card'
              entity: climate.heizung_buro
              fullscreen: false
            deviceID:
              - this
  - title: Temperaturen
    entities:
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.temperatur_wohnzimmer_lowboard
        noPadding: true
        cardOptions:
          entities:
            - sensor.temperatur_wohnzimmer_lowboard
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.temperatur_climate_bad
        noPadding: true
        cardOptions:
          entities:
            - sensor.temperatur_climate_bad
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.temperatur_climate_buero
        noPadding: true
        cardOptions:
          entities:
            - sensor.temperatur_climate_buero
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.temperatur_keller
        noPadding: true
        cardOptions:
          entities:
            - sensor.temperatur_keller
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.darksky_temperature
        noPadding: true
        cardOptions:
          entities:
            - sensor.darksky_temperature
  - title: Luftfeuchtigkeit
    entities:
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.darksky_humidity
        noPadding: true
        cardOptions:
          entities:
            - sensor.darksky_humidity
  - title: Luftfruck
    entities:
      - card: 'custom:mini-graph-card'
        tap_action:
          action: more-info
          entity: sensor.darksky_pressure
        noPadding: true
        cardOptions:
          entities:
            - sensor.darksky_pressure
```
